name: residences_ui
description: Charte graphique et composants partagés (bleu nuit, sable, blanc cassé).
publish_to: none
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.10.3
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
